spring:
  profiles:
    active: a
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/atp
      username: hanminglu
      password: hml188945
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    protocol: smtp #smtp是邮件发送协议，pop3和imap是邮件接收协议。因为我们要发送邮件，因此是smtp
    host: smtp.toutoujinrong.com #邮件发送服务器的主机，这里采用的是126邮箱来发送邮件
#    port: 25 #邮件发送服务器的端口
    auth: true #一般情况下，发送邮件都是要进行验证
    username: minglu@toutoujinrong.com #邮件发送服务器的用户名
    password: Hml@188945 #密码
    starttls:
      enable: true
      required: true